name = "GRDF"
uuid = "95533af7-be24-4180-ab8c-044114c62a3f"
authors = ["James <gholamja@cardiff.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
